title:              UVA Night Train Ultimate
email:              virginianighttrain@gmail.com
description:        
author:             UVA Night Train
baseurl:            "/"
url:                "https://uvanighttrain.com/"
#"https://nanduruganesh.github.io/NightTrainWebpage/"

# Social Profiles
twitter_username:   nighttrainatuva
github_username:    
facebook_username:  nighttrainultimate
instagram_username: nighttrainuva
linkedin_username:
youtube_username: "@nighttrainultimate7990"

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
