title:              UVA Night Train Ultimate
email:              virginianighttrain@gmail.com
description:        Men's Ultimate Frisbee at the University of Virginia
author:             UVA Night Train
baseurl:            "/"
url:                "https://nanduruganesh.github.io/NightTrainWebpage/"

# Social Profiles
twitter_username:   nighttrainatuva
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username: nighttrainuva
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
